# Jekyll configuration

# Explicitly include node_modules directory
include:
  - "build/node_modules/**"

# Don't process node_modules
keep_files:
  - "node_modules"

# Basic site settings
title: "Baby Jarvis"
baseurl: "" 